# Generated by Django 5.2.14 on 2026-05-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=100)),
                ("event_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
